snd-soc-opencores-i2s-objs := opencores_i2s.o
obj-$(CONFIG_SND_SOC_OPENCORES_I2S) += snd-soc-opencores-i2s.o

snd-soc-de1-soc-wm8731-objs := de1-soc-wm8731.o
obj-$(CONFIG_SND_SOC_DE1_SoC_WM8731) += snd-soc-de1-soc-wm8731.o

